# Generated by Django 5.1.4 on 2024-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardmodel_delete_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
