# Generated by Django 5.1.4 on 2024-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_local"'),
        ),
    ]
