# Generated by Django 5.1.4 on 2024-12-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_reactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionmodel',
            name='content',
            field=models.TextField(default='未設定'),
        ),
        migrations.AddField(
            model_name='reactionmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
