# Generated by Django 5.1.4 on 2024-12-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_sortmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortmodel',
            name='whichsort',
            field=models.BooleanField(default=False),
        ),
    ]
